name: "Issue to Project Auto Assign"
on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run custom action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_name: "template"
          project_number: 2
          target_column: "In Progress"
