name: Start Issue

on:
  create:

jobs:
  start-issue:
    if: github.ref_type == 'branch' && contains(github.ref, 'feature')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Start Issue
        uses: ./actions/start-issue
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_owner: 'jinhokim98'
          project_number: 2
          target_column: 'In Progress'
